# Generated by Django 3.1.2 on 2020-10-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_evento', models.CharField(max_length=20, verbose_name='DIA DEL EVENTO')),
                ('hora_evento', models.CharField(max_length=20, verbose_name='HORA DEL EVENTO')),
                ('tipo_evento', models.CharField(max_length=100, verbose_name='TIPO DE EVENTO')),
                ('numero_invitados', models.CharField(max_length=20, verbose_name='CAPACIDAD')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'db_table': 'eventos',
            },
        ),
    ]
