# Generated by Django 3.0.8 on 2020-10-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('octavo', models.IntegerField(default=0)),
                ('noveno', models.IntegerField(default=0)),
                ('decimo', models.IntegerField(default=0)),
                ('p_bachillerato', models.IntegerField(default=0)),
                ('s_bachillerato', models.IntegerField(default=0)),
                ('t_bachillerato', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DPsEstudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres_representante', models.CharField(max_length=100)),
                ('cedula_representante', models.IntegerField(default=0)),
                ('numero_celular_representante', models.IntegerField(default=0)),
                ('nombre_apellidos_padre', models.CharField(max_length=300)),
                ('cedula_padre', models.IntegerField(default=0)),
                ('numero_celular_padre', models.IntegerField(default=0)),
                ('ocupacion_padre', models.CharField(max_length=100)),
                ('nombre_apellidos_materno', models.CharField(max_length=300)),
                ('cedula_madre', models.IntegerField(default=0)),
                ('numero_celular_madre', models.IntegerField(default=0)),
                ('ocupacion_madre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cedula', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('hora', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_alumno', models.IntegerField(default=0)),
                ('nombres_materias', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_docente', models.CharField(max_length=100)),
                ('apellidos_docente', models.CharField(max_length=100)),
                ('materia_impartida', models.CharField(max_length=200)),
            ],
        ),
    ]
